package pl.edu.mimuw.nesc.compilation;

import pl.edu.mimuw.nesc.problem.NescError;
import pl.edu.mimuw.nesc.problem.NescWarning;

/**
 * <p>Interface that allows listening events that are generated by the compiler.
 * Currently, the events are warnings and errors that are detected during
 * compilation.</p>
 *
 * @author Michał Ciszewski <michal.ciszewski@students.mimuw.edu.pl>
 */
public interface CompilationListener {
    /**
     * An error has been detected by the compiler.
     *
     * @param error Error that has been detected.
     */
    void error(NescError error);

    /**
     * A warning is generated by the compiler.
     *
     * @param warning Warning that has been generated.
     */
    void warning(NescWarning warning);
}
