package pl.edu.mimuw.nesc.ast.util;

import org.junit.Test;
import pl.edu.mimuw.nesc.ast.util.NameMangler;

import static org.junit.Assert.assertEquals;

/**
 * Tests for the name mangling class.
 *
 * @author Michał Ciszewski <michal.ciszewski@students.mimuw.edu.pl>
 * @see pl.edu.mimuw.nesc.ast.util.NameMangler
 */
public final class NameManglerTest {
    @Test
    public void correctMangling() {
        final String[] unmangledNames = {
            "lfbg", "punyzyrr", "gyqqg", "punyzyrr", "lfbg", "knx",
            "lfbg", "ozaavu", "lfbg", "lfbg", "xfdwyefzr", "punyzyrr",
            "punyzyrr", "knx", "hdiamyb", "gyqqg", "ozaavu", "ozaavu",
            "ozaavu", "pc", "pc", "xfdwyefzr", "xfdwyefzr", "d",
            "knx", "hdiamyb", "gyqqg", "oszetijcsa", "gyqqg", "ozaavu",
            "gyqqg", "punyzyrr", "d", "d", "knx", "lfbg",
            "gyqqg", "punyzyrr", "pc", "ozaavu", "lfbg", "pc",
            "pc", "ozaavu", "ozaavu", "oszetijcsa", "pc", "punyzyrr",
            "lfbg", "gyqqg", "knx", "oszetijcsa", "ozaavu", "gyqqg",
            "knx", "lfbg", "punyzyrr", "punyzyrr", "hdiamyb", "lfbg",
            "lfbg", "d", "xfdwyefzr", "punyzyrr", "oszetijcsa", "xfdwyefzr",
            "punyzyrr", "gyqqg", "pc", "lfbg", "hdiamyb", "ozaavu",
            "knx", "xfdwyefzr", "oszetijcsa", "lfbg", "pc", "knx",
            "oszetijcsa", "oszetijcsa", "lfbg", "punyzyrr", "pc", "ozaavu",
            "oszetijcsa", "gyqqg", "gyqqg", "ozaavu", "ozaavu", "xfdwyefzr",
            "hdiamyb", "punyzyrr", "xfdwyefzr", "oszetijcsa", "pc", "lfbg",
            "gyqqg", "hdiamyb", "ozaavu", "lfbg", "lfbg", "lfbg",
            "lfbg", "gyqqg", "pc", "ozaavu", "lfbg", "oszetijcsa",
            "lfbg", "gyqqg", "xfdwyefzr", "xfdwyefzr", "lfbg", "ozaavu",
            "hdiamyb", "ozaavu", "lfbg", "pc", "pc", "punyzyrr",
            "xfdwyefzr", "lfbg", "pc", "xfdwyefzr", "xfdwyefzr", "oszetijcsa",
            "d", "knx", "xfdwyefzr", "gyqqg", "gyqqg", "knx",
            "hdiamyb", "oszetijcsa", "ozaavu", "punyzyrr", "lfbg", "hdiamyb",
            "pc", "pc", "lfbg", "knx", "oszetijcsa", "knx",
            "ozaavu", "punyzyrr", "hdiamyb", "oszetijcsa", "hdiamyb", "ozaavu",
            "d", "punyzyrr", "xfdwyefzr", "xfdwyefzr", "pc", "pc",
            "lfbg", "pc", "knx", "pc", "lfbg", "xfdwyefzr",
            "oszetijcsa", "oszetijcsa", "xfdwyefzr", "lfbg", "lfbg", "knx",
            "hdiamyb", "knx", "ozaavu", "gyqqg", "d", "ozaavu",
            "hdiamyb", "hdiamyb", "ozaavu", "xfdwyefzr", "lfbg", "hdiamyb",
            "punyzyrr", "punyzyrr", "ozaavu", "gyqqg", "knx", "knx",
            "ozaavu", "hdiamyb", "pc", "d", "punyzyrr", "knx",
            "oszetijcsa", "ozaavu", "xfdwyefzr", "xfdwyefzr", "pc", "lfbg",
            "hdiamyb", "oszetijcsa", "gyqqg", "punyzyrr", "hdiamyb", "oszetijcsa",
            "hdiamyb", "knx", "knx", "hdiamyb", "knx", "gyqqg",
            "xfdwyefzr", "lfbg", "d", "xfdwyefzr", "pc", "gyqqg",
            "oszetijcsa", "oszetijcsa", "lfbg", "oszetijcsa", "xfdwyefzr", "gyqqg",
            "lfbg", "gyqqg", "d", "oszetijcsa", "punyzyrr", "xfdwyefzr",
            "hdiamyb", "punyzyrr", "lfbg", "ozaavu", "knx", "oszetijcsa",
            "hdiamyb", "hdiamyb", "ozaavu", "gyqqg", "ozaavu", "ozaavu",
            "hdiamyb", "pc", "xfdwyefzr", "punyzyrr", "hdiamyb", "lfbg",
            "ozaavu", "punyzyrr", "gyqqg", "d", "punyzyrr", "ozaavu",
            "gyqqg", "pc", "oszetijcsa", "pc", "d", "lfbg",
            "punyzyrr", "pc", "xfdwyefzr", "pc", "ozaavu", "pc",
            "punyzyrr", "hdiamyb", "punyzyrr", "pc", "d", "d",
            "oszetijcsa", "pc", "gyqqg", "oszetijcsa", "knx", "pc",
            "pc", "lfbg", "hdiamyb", "knx", "gyqqg", "hdiamyb",
            "hdiamyb", "lfbg", "oszetijcsa", "ozaavu", "oszetijcsa", "pc",
            "oszetijcsa", "ozaavu", "xfdwyefzr", "hdiamyb", "xfdwyefzr", "gyqqg",
            "punyzyrr", "xfdwyefzr", "knx", "knx", "ozaavu", "hdiamyb",
            "pc", "ozaavu", "oszetijcsa", "oszetijcsa", "punyzyrr", "knx",
            "pc", "gyqqg", "ozaavu", "ozaavu", "punyzyrr", "ozaavu",
            "oszetijcsa", "xfdwyefzr", "gyqqg", "d", "knx", "knx",
            "d", "pc", "punyzyrr", "pc", "knx", "punyzyrr",
            "d", "lfbg", "xfdwyefzr", "gyqqg", "gyqqg", "xfdwyefzr",
            "d", "knx", "oszetijcsa", "d", "pc", "punyzyrr",
            "d", "lfbg", "d", "punyzyrr", "d", "ozaavu",
            "pc", "oszetijcsa", "knx", "hdiamyb", "gyqqg", "xfdwyefzr",
            "oszetijcsa", "hdiamyb", "gyqqg", "knx", "punyzyrr", "hdiamyb",
            "knx", "knx", "pc", "xfdwyefzr", "punyzyrr", "oszetijcsa",
            "pc", "knx", "lfbg", "oszetijcsa", "oszetijcsa", "hdiamyb",
            "pc", "punyzyrr", "lfbg", "d", "lfbg", "d",
            "punyzyrr", "oszetijcsa", "ozaavu", "hdiamyb", "pc", "gyqqg",
            "lfbg", "d", "gyqqg", "ozaavu", "hdiamyb", "d",
            "knx", "gyqqg", "pc", "knx", "hdiamyb", "ozaavu",
            "ozaavu", "gyqqg", "pc", "ozaavu", "gyqqg", "gyqqg",
            "gyqqg", "lfbg", "d", "pc", "gyqqg", "d",
            "knx", "punyzyrr", "lfbg", "hdiamyb", "gyqqg", "ozaavu",
            "xfdwyefzr", "oszetijcsa", "gyqqg", "oszetijcsa", "d", "lfbg",
            "oszetijcsa", "pc", "d", "xfdwyefzr", "lfbg", "xfdwyefzr",
            "gyqqg", "oszetijcsa", "punyzyrr", "pc", "d", "pc",
            "gyqqg", "hdiamyb", "hdiamyb", "lfbg", "lfbg", "hdiamyb",
            "gyqqg", "ozaavu", "knx", "punyzyrr", "pc", "gyqqg",
            "xfdwyefzr", "pc", "d", "gyqqg", "punyzyrr", "oszetijcsa",
            "d", "xfdwyefzr", "pc", "gyqqg", "oszetijcsa", "hdiamyb",
            "pc", "gyqqg", "xfdwyefzr", "oszetijcsa", "pc", "pc",
            "ozaavu", "punyzyrr", "gyqqg", "xfdwyefzr", "ozaavu", "lfbg",
            "d", "d", "hdiamyb", "lfbg", "oszetijcsa", "punyzyrr",
            "d", "ozaavu", "oszetijcsa", "ozaavu", "ozaavu", "lfbg",
            "gyqqg", "hdiamyb", "ozaavu", "d", "gyqqg", "punyzyrr",
            "d", "xfdwyefzr", "knx", "knx", "oszetijcsa", "lfbg",
            "oszetijcsa", "hdiamyb", "knx", "oszetijcsa", "ozaavu", "punyzyrr",
            "xfdwyefzr", "knx", "oszetijcsa", "punyzyrr", "lfbg", "knx",
            "pc", "lfbg", "d", "knx", "lfbg", "xfdwyefzr",
            "oszetijcsa", "hdiamyb", "pc", "pc", "xfdwyefzr", "hdiamyb",
            "hdiamyb", "oszetijcsa", "ozaavu", "gyqqg", "oszetijcsa", "gyqqg",
            "hdiamyb", "knx", "hdiamyb", "hdiamyb", "pc", "gyqqg",
            "punyzyrr", "oszetijcsa", "xfdwyefzr", "lfbg", "hdiamyb", "pc",
            "punyzyrr", "gyqqg", "punyzyrr", "knx", "lfbg", "knx",
            "lfbg", "gyqqg", "hdiamyb", "oszetijcsa", "lfbg", "lfbg",
            "lfbg", "xfdwyefzr", "d", "knx", "knx", "knx",
            "knx", "pc", "pc", "ozaavu", "oszetijcsa", "lfbg",
            "ozaavu", "pc", "knx", "d", "d", "pc",
            "xfdwyefzr", "d", "punyzyrr", "knx", "pc", "oszetijcsa",
            "lfbg", "pc", "punyzyrr", "hdiamyb", "punyzyrr", "gyqqg",
            "ozaavu", "hdiamyb", "pc", "oszetijcsa", "punyzyrr", "oszetijcsa",
            "punyzyrr", "ozaavu", "oszetijcsa", "pc", "ozaavu", "punyzyrr",
            "pc", "xfdwyefzr", "gyqqg", "d", "ozaavu", "punyzyrr",
            "d", "pc", "pc", "ozaavu", "lfbg", "ozaavu",
            "gyqqg", "hdiamyb", "gyqqg", "pc", "oszetijcsa", "ozaavu",
            "d", "lfbg", "knx", "punyzyrr", "ozaavu", "ozaavu",
            "xfdwyefzr", "hdiamyb", "gyqqg", "xfdwyefzr", "punyzyrr", "knx",
            "pc", "knx", "lfbg", "oszetijcsa", "lfbg", "pc",
            "oszetijcsa", "knx", "xfdwyefzr", "knx", "knx", "xfdwyefzr",
            "ozaavu", "oszetijcsa", "punyzyrr", "hdiamyb", "lfbg", "punyzyrr",
            "punyzyrr", "hdiamyb", "hdiamyb", "ozaavu", "gyqqg", "xfdwyefzr",
            "punyzyrr", "knx", "knx", "xfdwyefzr", "lfbg", "xfdwyefzr",
            "knx", "punyzyrr", "pc", "ozaavu", "lfbg", "gyqqg",
            "knx", "xfdwyefzr", "hdiamyb", "hdiamyb", "xfdwyefzr", "d",
            "punyzyrr", "pc", "punyzyrr", "gyqqg", "ozaavu", "hdiamyb",
            "pc", "d", "oszetijcsa", "d", "hdiamyb", "oszetijcsa",
            "d", "gyqqg", "oszetijcsa", "hdiamyb", "d", "knx",
            "xfdwyefzr", "hdiamyb", "punyzyrr", "hdiamyb", "gyqqg", "knx",
            "lfbg", "punyzyrr", "hdiamyb", "ozaavu", "d", "ozaavu",
            "lfbg", "punyzyrr", "hdiamyb", "pc", "xfdwyefzr", "pc",
            "gyqqg", "hdiamyb", "hdiamyb", "punyzyrr", "ozaavu", "lfbg",
            "punyzyrr", "hdiamyb", "xfdwyefzr", "punyzyrr", "d", "punyzyrr",
        };

        final String[] expectedMangledNames = {
            "lfbg__a", "punyzyrr__b", "gyqqg__c", "punyzyrr__d", "lfbg__e", "knx__f",
            "lfbg__g", "ozaavu__h", "lfbg__i", "lfbg__j", "xfdwyefzr__k", "punyzyrr__l",
            "punyzyrr__m", "knx__n", "hdiamyb__o", "gyqqg__p", "ozaavu__q", "ozaavu__r",
            "ozaavu__s", "pc__t", "pc__u", "xfdwyefzr__v", "xfdwyefzr__w", "d__x",
            "knx__y", "hdiamyb__z", "gyqqg__aa", "oszetijcsa__ab", "gyqqg__ac", "ozaavu__ad",
            "gyqqg__ae", "punyzyrr__af", "d__ag", "d__ah", "knx__ai", "lfbg__aj",
            "gyqqg__ak", "punyzyrr__al", "pc__am", "ozaavu__an", "lfbg__ao", "pc__ap",
            "pc__aq", "ozaavu__ar", "ozaavu__as", "oszetijcsa__at", "pc__au", "punyzyrr__av",
            "lfbg__aw", "gyqqg__ax", "knx__ay", "oszetijcsa__az", "ozaavu__ba", "gyqqg__bb",
            "knx__bc", "lfbg__bd", "punyzyrr__be", "punyzyrr__bf", "hdiamyb__bg", "lfbg__bh",
            "lfbg__bi", "d__bj", "xfdwyefzr__bk", "punyzyrr__bl", "oszetijcsa__bm", "xfdwyefzr__bn",
            "punyzyrr__bo", "gyqqg__bp", "pc__bq", "lfbg__br", "hdiamyb__bs", "ozaavu__bt",
            "knx__bu", "xfdwyefzr__bv", "oszetijcsa__bw", "lfbg__bx", "pc__by", "knx__bz",
            "oszetijcsa__ca", "oszetijcsa__cb", "lfbg__cc", "punyzyrr__cd", "pc__ce", "ozaavu__cf",
            "oszetijcsa__cg", "gyqqg__ch", "gyqqg__ci", "ozaavu__cj", "ozaavu__ck", "xfdwyefzr__cl",
            "hdiamyb__cm", "punyzyrr__cn", "xfdwyefzr__co", "oszetijcsa__cp", "pc__cq", "lfbg__cr",
            "gyqqg__cs", "hdiamyb__ct", "ozaavu__cu", "lfbg__cv", "lfbg__cw", "lfbg__cx",
            "lfbg__cy", "gyqqg__cz", "pc__da", "ozaavu__db", "lfbg__dc", "oszetijcsa__dd",
            "lfbg__de", "gyqqg__df", "xfdwyefzr__dg", "xfdwyefzr__dh", "lfbg__di", "ozaavu__dj",
            "hdiamyb__dk", "ozaavu__dl", "lfbg__dm", "pc__dn", "pc__do", "punyzyrr__dp",
            "xfdwyefzr__dq", "lfbg__dr", "pc__ds", "xfdwyefzr__dt", "xfdwyefzr__du", "oszetijcsa__dv",
            "d__dw", "knx__dx", "xfdwyefzr__dy", "gyqqg__dz", "gyqqg__ea", "knx__eb",
            "hdiamyb__ec", "oszetijcsa__ed", "ozaavu__ee", "punyzyrr__ef", "lfbg__eg", "hdiamyb__eh",
            "pc__ei", "pc__ej", "lfbg__ek", "knx__el", "oszetijcsa__em", "knx__en",
            "ozaavu__eo", "punyzyrr__ep", "hdiamyb__eq", "oszetijcsa__er", "hdiamyb__es", "ozaavu__et",
            "d__eu", "punyzyrr__ev", "xfdwyefzr__ew", "xfdwyefzr__ex", "pc__ey", "pc__ez",
            "lfbg__fa", "pc__fb", "knx__fc", "pc__fd", "lfbg__fe", "xfdwyefzr__ff",
            "oszetijcsa__fg", "oszetijcsa__fh", "xfdwyefzr__fi", "lfbg__fj", "lfbg__fk", "knx__fl",
            "hdiamyb__fm", "knx__fn", "ozaavu__fo", "gyqqg__fp", "d__fq", "ozaavu__fr",
            "hdiamyb__fs", "hdiamyb__ft", "ozaavu__fu", "xfdwyefzr__fv", "lfbg__fw", "hdiamyb__fx",
            "punyzyrr__fy", "punyzyrr__fz", "ozaavu__ga", "gyqqg__gb", "knx__gc", "knx__gd",
            "ozaavu__ge", "hdiamyb__gf", "pc__gg", "d__gh", "punyzyrr__gi", "knx__gj",
            "oszetijcsa__gk", "ozaavu__gl", "xfdwyefzr__gm", "xfdwyefzr__gn", "pc__go", "lfbg__gp",
            "hdiamyb__gq", "oszetijcsa__gr", "gyqqg__gs", "punyzyrr__gt", "hdiamyb__gu", "oszetijcsa__gv",
            "hdiamyb__gw", "knx__gx", "knx__gy", "hdiamyb__gz", "knx__ha", "gyqqg__hb",
            "xfdwyefzr__hc", "lfbg__hd", "d__he", "xfdwyefzr__hf", "pc__hg", "gyqqg__hh",
            "oszetijcsa__hi", "oszetijcsa__hj", "lfbg__hk", "oszetijcsa__hl", "xfdwyefzr__hm", "gyqqg__hn",
            "lfbg__ho", "gyqqg__hp", "d__hq", "oszetijcsa__hr", "punyzyrr__hs", "xfdwyefzr__ht",
            "hdiamyb__hu", "punyzyrr__hv", "lfbg__hw", "ozaavu__hx", "knx__hy", "oszetijcsa__hz",
            "hdiamyb__ia", "hdiamyb__ib", "ozaavu__ic", "gyqqg__id", "ozaavu__ie", "ozaavu__if",
            "hdiamyb__ig", "pc__ih", "xfdwyefzr__ii", "punyzyrr__ij", "hdiamyb__ik", "lfbg__il",
            "ozaavu__im", "punyzyrr__in", "gyqqg__io", "d__ip", "punyzyrr__iq", "ozaavu__ir",
            "gyqqg__is", "pc__it", "oszetijcsa__iu", "pc__iv", "d__iw", "lfbg__ix",
            "punyzyrr__iy", "pc__iz", "xfdwyefzr__ja", "pc__jb", "ozaavu__jc", "pc__jd",
            "punyzyrr__je", "hdiamyb__jf", "punyzyrr__jg", "pc__jh", "d__ji", "d__jj",
            "oszetijcsa__jk", "pc__jl", "gyqqg__jm", "oszetijcsa__jn", "knx__jo", "pc__jp",
            "pc__jq", "lfbg__jr", "hdiamyb__js", "knx__jt", "gyqqg__ju", "hdiamyb__jv",
            "hdiamyb__jw", "lfbg__jx", "oszetijcsa__jy", "ozaavu__jz", "oszetijcsa__ka", "pc__kb",
            "oszetijcsa__kc", "ozaavu__kd", "xfdwyefzr__ke", "hdiamyb__kf", "xfdwyefzr__kg", "gyqqg__kh",
            "punyzyrr__ki", "xfdwyefzr__kj", "knx__kk", "knx__kl", "ozaavu__km", "hdiamyb__kn",
            "pc__ko", "ozaavu__kp", "oszetijcsa__kq", "oszetijcsa__kr", "punyzyrr__ks", "knx__kt",
            "pc__ku", "gyqqg__kv", "ozaavu__kw", "ozaavu__kx", "punyzyrr__ky", "ozaavu__kz",
            "oszetijcsa__la", "xfdwyefzr__lb", "gyqqg__lc", "d__ld", "knx__le", "knx__lf",
            "d__lg", "pc__lh", "punyzyrr__li", "pc__lj", "knx__lk", "punyzyrr__ll",
            "d__lm", "lfbg__ln", "xfdwyefzr__lo", "gyqqg__lp", "gyqqg__lq", "xfdwyefzr__lr",
            "d__ls", "knx__lt", "oszetijcsa__lu", "d__lv", "pc__lw", "punyzyrr__lx",
            "d__ly", "lfbg__lz", "d__ma", "punyzyrr__mb", "d__mc", "ozaavu__md",
            "pc__me", "oszetijcsa__mf", "knx__mg", "hdiamyb__mh", "gyqqg__mi", "xfdwyefzr__mj",
            "oszetijcsa__mk", "hdiamyb__ml", "gyqqg__mm", "knx__mn", "punyzyrr__mo", "hdiamyb__mp",
            "knx__mq", "knx__mr", "pc__ms", "xfdwyefzr__mt", "punyzyrr__mu", "oszetijcsa__mv",
            "pc__mw", "knx__mx", "lfbg__my", "oszetijcsa__mz", "oszetijcsa__na", "hdiamyb__nb",
            "pc__nc", "punyzyrr__nd", "lfbg__ne", "d__nf", "lfbg__ng", "d__nh",
            "punyzyrr__ni", "oszetijcsa__nj", "ozaavu__nk", "hdiamyb__nl", "pc__nm", "gyqqg__nn",
            "lfbg__no", "d__np", "gyqqg__nq", "ozaavu__nr", "hdiamyb__ns", "d__nt",
            "knx__nu", "gyqqg__nv", "pc__nw", "knx__nx", "hdiamyb__ny", "ozaavu__nz",
            "ozaavu__oa", "gyqqg__ob", "pc__oc", "ozaavu__od", "gyqqg__oe", "gyqqg__of",
            "gyqqg__og", "lfbg__oh", "d__oi", "pc__oj", "gyqqg__ok", "d__ol",
            "knx__om", "punyzyrr__on", "lfbg__oo", "hdiamyb__op", "gyqqg__oq", "ozaavu__or",
            "xfdwyefzr__os", "oszetijcsa__ot", "gyqqg__ou", "oszetijcsa__ov", "d__ow", "lfbg__ox",
            "oszetijcsa__oy", "pc__oz", "d__pa", "xfdwyefzr__pb", "lfbg__pc", "xfdwyefzr__pd",
            "gyqqg__pe", "oszetijcsa__pf", "punyzyrr__pg", "pc__ph", "d__pi", "pc__pj",
            "gyqqg__pk", "hdiamyb__pl", "hdiamyb__pm", "lfbg__pn", "lfbg__po", "hdiamyb__pp",
            "gyqqg__pq", "ozaavu__pr", "knx__ps", "punyzyrr__pt", "pc__pu", "gyqqg__pv",
            "xfdwyefzr__pw", "pc__px", "d__py", "gyqqg__pz", "punyzyrr__qa", "oszetijcsa__qb",
            "d__qc", "xfdwyefzr__qd", "pc__qe", "gyqqg__qf", "oszetijcsa__qg", "hdiamyb__qh",
            "pc__qi", "gyqqg__qj", "xfdwyefzr__qk", "oszetijcsa__ql", "pc__qm", "pc__qn",
            "ozaavu__qo", "punyzyrr__qp", "gyqqg__qq", "xfdwyefzr__qr", "ozaavu__qs", "lfbg__qt",
            "d__qu", "d__qv", "hdiamyb__qw", "lfbg__qx", "oszetijcsa__qy", "punyzyrr__qz",
            "d__ra", "ozaavu__rb", "oszetijcsa__rc", "ozaavu__rd", "ozaavu__re", "lfbg__rf",
            "gyqqg__rg", "hdiamyb__rh", "ozaavu__ri", "d__rj", "gyqqg__rk", "punyzyrr__rl",
            "d__rm", "xfdwyefzr__rn", "knx__ro", "knx__rp", "oszetijcsa__rq", "lfbg__rr",
            "oszetijcsa__rs", "hdiamyb__rt", "knx__ru", "oszetijcsa__rv", "ozaavu__rw", "punyzyrr__rx",
            "xfdwyefzr__ry", "knx__rz", "oszetijcsa__sa", "punyzyrr__sb", "lfbg__sc", "knx__sd",
            "pc__se", "lfbg__sf", "d__sg", "knx__sh", "lfbg__si", "xfdwyefzr__sj",
            "oszetijcsa__sk", "hdiamyb__sl", "pc__sm", "pc__sn", "xfdwyefzr__so", "hdiamyb__sp",
            "hdiamyb__sq", "oszetijcsa__sr", "ozaavu__ss", "gyqqg__st", "oszetijcsa__su", "gyqqg__sv",
            "hdiamyb__sw", "knx__sx", "hdiamyb__sy", "hdiamyb__sz", "pc__ta", "gyqqg__tb",
            "punyzyrr__tc", "oszetijcsa__td", "xfdwyefzr__te", "lfbg__tf", "hdiamyb__tg", "pc__th",
            "punyzyrr__ti", "gyqqg__tj", "punyzyrr__tk", "knx__tl", "lfbg__tm", "knx__tn",
            "lfbg__to", "gyqqg__tp", "hdiamyb__tq", "oszetijcsa__tr", "lfbg__ts", "lfbg__tt",
            "lfbg__tu", "xfdwyefzr__tv", "d__tw", "knx__tx", "knx__ty", "knx__tz",
            "knx__ua", "pc__ub", "pc__uc", "ozaavu__ud", "oszetijcsa__ue", "lfbg__uf",
            "ozaavu__ug", "pc__uh", "knx__ui", "d__uj", "d__uk", "pc__ul",
            "xfdwyefzr__um", "d__un", "punyzyrr__uo", "knx__up", "pc__uq", "oszetijcsa__ur",
            "lfbg__us", "pc__ut", "punyzyrr__uu", "hdiamyb__uv", "punyzyrr__uw", "gyqqg__ux",
            "ozaavu__uy", "hdiamyb__uz", "pc__va", "oszetijcsa__vb", "punyzyrr__vc", "oszetijcsa__vd",
            "punyzyrr__ve", "ozaavu__vf", "oszetijcsa__vg", "pc__vh", "ozaavu__vi", "punyzyrr__vj",
            "pc__vk", "xfdwyefzr__vl", "gyqqg__vm", "d__vn", "ozaavu__vo", "punyzyrr__vp",
            "d__vq", "pc__vr", "pc__vs", "ozaavu__vt", "lfbg__vu", "ozaavu__vv",
            "gyqqg__vw", "hdiamyb__vx", "gyqqg__vy", "pc__vz", "oszetijcsa__wa", "ozaavu__wb",
            "d__wc", "lfbg__wd", "knx__we", "punyzyrr__wf", "ozaavu__wg", "ozaavu__wh",
            "xfdwyefzr__wi", "hdiamyb__wj", "gyqqg__wk", "xfdwyefzr__wl", "punyzyrr__wm", "knx__wn",
            "pc__wo", "knx__wp", "lfbg__wq", "oszetijcsa__wr", "lfbg__ws", "pc__wt",
            "oszetijcsa__wu", "knx__wv", "xfdwyefzr__ww", "knx__wx", "knx__wy", "xfdwyefzr__wz",
            "ozaavu__xa", "oszetijcsa__xb", "punyzyrr__xc", "hdiamyb__xd", "lfbg__xe", "punyzyrr__xf",
            "punyzyrr__xg", "hdiamyb__xh", "hdiamyb__xi", "ozaavu__xj", "gyqqg__xk", "xfdwyefzr__xl",
            "punyzyrr__xm", "knx__xn", "knx__xo", "xfdwyefzr__xp", "lfbg__xq", "xfdwyefzr__xr",
            "knx__xs", "punyzyrr__xt", "pc__xu", "ozaavu__xv", "lfbg__xw", "gyqqg__xx",
            "knx__xy", "xfdwyefzr__xz", "hdiamyb__ya", "hdiamyb__yb", "xfdwyefzr__yc", "d__yd",
            "punyzyrr__ye", "pc__yf", "punyzyrr__yg", "gyqqg__yh", "ozaavu__yi", "hdiamyb__yj",
            "pc__yk", "d__yl", "oszetijcsa__ym", "d__yn", "hdiamyb__yo", "oszetijcsa__yp",
            "d__yq", "gyqqg__yr", "oszetijcsa__ys", "hdiamyb__yt", "d__yu", "knx__yv",
            "xfdwyefzr__yw", "hdiamyb__yx", "punyzyrr__yy", "hdiamyb__yz", "gyqqg__za", "knx__zb",
            "lfbg__zc", "punyzyrr__zd", "hdiamyb__ze", "ozaavu__zf", "d__zg", "ozaavu__zh",
            "lfbg__zi", "punyzyrr__zj", "hdiamyb__zk", "pc__zl", "xfdwyefzr__zm", "pc__zn",
            "gyqqg__zo", "hdiamyb__zp", "hdiamyb__zq", "punyzyrr__zr", "ozaavu__zs", "lfbg__zt",
            "punyzyrr__zu", "hdiamyb__zv", "xfdwyefzr__zw", "punyzyrr__zx", "d__zy", "punyzyrr__zz",
        };

        final NameMangler mangler = NameMangler.getInstance();

        // Check the mangling

        for (int i = 0; i < unmangledNames.length; ++i) {
            assertEquals(expectedMangledNames[i], mangler.mangle(unmangledNames[i]));
        }
    }
}
